# !!! This compose file only for development use
version: '3.8'
services:
  mongo:
    image: bitnami/mongodb:5.0.8
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ADVERTISED_HOSTNAME=mongo
      - MONGODB_REPLICA_SET_NAME=laf
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ENABLE_DIRECTORY_PER_DB=yes
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_USERNAME=my_user
      - MONGODB_PASSWORD=password123
      - MONGODB_DATABASE=laf-sys
    volumes:
      - db-data:/bitnami/mongodb
    ports:
      - "27017:27017"
    networks:
      - laf_shared_network

  oss:
    image: 'bitnami/minio:2022.4.12'
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=oss/data/{0...3}
      - MINIO_SKIP_CLIENT=yes
      - MINIO_REGION_NAME=cn-default
      - MINIO_DOMAIN=oss.127-0-0-1.nip.io
    ports:
      - "9020:9000"
      - "9120:9001"
    volumes:
      - oss-data:/data
    networks:
      - laf_shared_network

  system-server:
    build: ./packages/system-server
    user: root
    working_dir: /app
    environment:
      SYS_DB_URI: mongodb://my_user:password123@mongo:27017/?authSource=laf-sys&replicaSet=laf&writeConcern=majority
      APP_DB_URI: mongodb://root:password123@mongo:27017/?authSource=admin&replicaSet=laf&writeConcern=majority
      SYS_SERVER_SECRET_SALT: Rewrite_Your_Own_Secret_Salt_abcdefg1234567
      LOG_LEVEL: debug
      ACCOUNT_DEFAULT_APP_QUOTA: 5
      APP_SERVICE_IMAGE: lafyun/app-service:latest
      APP_SERVICE_DEPLOY_HOST: 127-0-0-1.nip.io:8080 # `*.127-0-0-1.nip.io` always resolved to 127.0.0.1, used to local development
      APP_SERVICE_DEPLOY_URL_SCHEMA: 'http'
      MINIO_ACCESS_KEY: minio-root-user
      MINIO_ACCESS_SECRET: minio-root-password
      MINIO_INTERNAL_ENDPOINT: http://oss:9000
      MINIO_EXTERNAL_ENDPOINT: http://oss.127-0-0-1.nip.io:8080
      MINIO_REGION_NAME: cn-default
      INIT_ROOT_ACCOUNT_PASSWORD: abc123
      INIT_ROOT_ACCOUNT: root
      SYSTEM_EXTENSION_APPID: '000000'
      APPID_LENGTH: 6
    command: dockerize -wait tcp://mongo:27017 -wait http://oss:9001 -timeout 60s sh /app/start.sh
    volumes:
      - ./packages/system-server:/app
      - ./packages/database-proxy:/app/node_modules/database-proxy:ro
      - ./packages/database-ql:/app/node_modules/database-ql:ro
      - ./packages/database-ql:/app/node_modules/database-proxy/node_modules/database-ql:ro
    ports:
      - "9000"
    depends_on:
      - mongo
    restart: always
    networks:
      - laf_shared_network

  instance-controller:
    build: ./packages/instance-controller
    user: root
    working_dir: /app
    environment:
      SCHEDULER_INTERVAL: 1000
      SYS_DB_URI: mongodb://my_user:password123@mongo:27017/?authSource=laf-sys&replicaSet=laf&writeConcern=majority
      APP_DB_URI: mongodb://root:password123@mongo:27017/?authSource=admin&replicaSet=laf&writeConcern=majority
      SHARED_NETWORK: laf_shared_network
      LOG_LEVEL: debug
      SERVICE_DRIVER: docker
      APP_SERVICE_ENV_NPM_INSTALL_FLAGS: '--registry=https://registry.npm.taobao.org --no-audit --no-fund'
      MINIO_INTERNAL_ENDPOINT: http://oss:9000
      MINIO_EXTERNAL_ENDPOINT: http://oss.127-0-0-1.nip.io:8080
      MINIO_REGION_NAME: cn-default
      DEBUG_BIND_HOST_APP_PATH: '${PWD}/packages/app-service'
      SYSTEM_EXTENSION_APPID: '000000'
    command: node ./dist/index.js
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./packages/instance-controller:/app
    ports:
      - "9000"
    depends_on:
      - mongo
    restart: always
    networks:
      - laf_shared_network

  gateway:
    image: openresty/openresty:latest
    depends_on:
      - mongo
      - system-server
    environment:
      DEPLOY_DOMAIN: "*.127-0-0-1.nip.io" # `*.127-0-0-1.nip.io` always resolved to 127.0.0.1, used to local development
      DEPLOY_OSS_DOMAIN: "oss.127-0-0-1.nip.io"
      SYS_CLIENT_HOST: console.127-0-0-1.nip.io
      SYSTEM_EXTENSION_APPID: '000000'
    volumes:
      - ./packages/gateway/scripts:/scripts
      - ./packages/gateway/conf.docker:/conf.docker
    command: "sh /scripts/start.sh"
    ports:
      - 8080:80
    networks:
      - laf_shared_network

  system-client:
    build: ./packages/system-client
    volumes:
      - ./packages/system-client/dist:/app
    networks:
      - laf_shared_network

  app-console:
    build: ./packages/app-console
    volumes:
      - ./packages/app-console/dist:/app
    networks:
      - laf_shared_network

volumes:
  db-data:
  oss-data:
  etcd-data:


networks:
  laf_shared_network:
    external: true
