version: '3.8'
services:
  mongo:
    image: bitnami/mongodb:5.0.8
    # image: bitnami/mongodb:4.4.13    # Use this version for Apple M1 Chip
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ADVERTISED_HOSTNAME=mongo
      - MONGODB_REPLICA_SET_NAME=laf
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ENABLE_DIRECTORY_PER_DB=yes
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_DATABASE=${SYS_DB}
      - MONGODB_USERNAME=${SYS_DB_USER}
      - MONGODB_PASSWORD=${SYS_DB_PASSWORD}
    volumes:
      - db-data:/bitnami/mongodb
    ports:
      - "27017:27017"
    networks:
      - laf_shared_network

  oss:
    image: 'bitnami/minio:2022.4.12'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=oss/data/{0...3}
      - MINIO_ETCD_ENDPOINTS=http://etcd:2379
      - MINIO_SKIP_CLIENT=yes
      - MINIO_REGION_NAME=cn-default
      - MINIO_DOMAIN=${OSS_DOMAIN}
    ports:
      - "9020:9000"
      - "9120:9001"
    volumes:
      - oss-data:/data
    networks:
      - laf_shared_network

  etcd:
    image: 'bitnami/etcd:3.5.4'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    volumes:
      - etcd-data:/bitnami/etcd/data
    ports:
      - 2379
      - 2380
    networks:
      - laf_shared_network

  system-server:
    image: lafyun/system-server:0.8.0
    user: root
    working_dir: /app
    environment:
      SYS_DB_URI: mongodb://${SYS_DB_USER}:${SYS_DB_PASSWORD}@mongo:27017/?authSource=${SYS_DB}&replicaSet=laf&writeConcern=majority
      APP_DB_URI: mongodb://root:${MONGODB_ROOT_PASSWORD}@mongo:27017/?authSource=admin&replicaSet=laf&writeConcern=majority
      SYS_SERVER_SECRET_SALT: ${SYS_SERVER_SECRET_SALT}
      SHARED_NETWORK: laf_shared_network
      LOG_LEVEL: ${LOG_LEVEL:-debug}
      APP_SERVICE_IMAGE: ${APP_SERVICE_IMAGE:-lafyun/app-service:latest}
      ACCOUNT_DEFAULT_APP_QUOTA: ${ACCOUNT_DEFAULT_APP_QUOTA:-2}
      APP_SERVICE_DEPLOY_HOST: ${DEPLOY_DOMAIN:?err}:${PUBLISH_PORT:-8080}
      APP_SERVICE_DEPLOY_URL_SCHEMA: ${APP_SERVICE_DEPLOY_URL_SCHEMA}
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_ACCESS_SECRET: ${MINIO_ROOT_PASSWORD}
      MINIO_INTERNAL_ENDPOINT: http://oss:9000
      MINIO_EXTERNAL_ENDPOINT: http://${OSS_DOMAIN}:${PUBLISH_PORT:-8080}
      MINIO_REGION_NAME: cn-default
      INIT_ROOT_ACCOUNT: ${INIT_ROOT_ACCOUNT}
      INIT_ROOT_ACCOUNT_PASSWORD: ${INIT_ROOT_ACCOUNT_PASSWORD:?err}
      SYSTEM_EXTENSION_APPID: ${SYSTEM_EXTENSION_APPID}
      APPID_LENGTH: 6
    command: dockerize -wait tcp://mongo:27017 -wait http://oss:9001 -timeout 60s sh /app/start.sh
    depends_on:
      - mongo
    cap_drop:
      - ALL
    tmpfs:
      - /tmp
    restart: always
    networks:
      - laf_shared_network

  gateway:
    image: lafyun/gateway:0.8.0-alpha.3
    depends_on:
      - system-server
      - mongo
    environment:
      DEPLOY_DOMAIN: "*.${DEPLOY_DOMAIN:?err}"
      DEPLOY_OSS_DOMAIN: ${OSS_DOMAIN}
      SYS_CLIENT_HOST: ${SYS_CLIENT_HOST:?err}
      SYSTEM_EXTENSION_APPID: ${SYSTEM_EXTENSION_APPID}
    command: "sh /scripts/start.sh"
    ports:
      - ${PUBLISH_PORT:-8080}:80
    networks:
      - laf_shared_network

  instance-controller:
    image: lafyun/instance-controller:0.8.0
    user: root
    working_dir: /app
    environment:
      SCHEDULER_INTERVAL: 1000
      SYS_DB_URI: mongodb://${SYS_DB_USER}:${SYS_DB_PASSWORD}@mongo:27017/?authSource=${SYS_DB}&replicaSet=laf&writeConcern=majority
      APP_DB_URI: mongodb://root:${MONGODB_ROOT_PASSWORD}@mongo:27017/?authSource=admin&replicaSet=laf&writeConcern=majority
      SHARED_NETWORK: laf_shared_network
      LOG_LEVEL: debug
      SERVICE_DRIVER: docker
      APP_SERVICE_ENV_NPM_INSTALL_FLAGS: '--registry=https://registry.npm.taobao.org --no-audit --no-fund'
      MINIO_INTERNAL_ENDPOINT: http://oss:9000
      MINIO_EXTERNAL_ENDPOINT: http://${OSS_DOMAIN}:${PUBLISH_PORT:-8080}
      MINIO_REGION_NAME: cn-default
      SYSTEM_EXTENSION_APPID: ${SYSTEM_EXTENSION_APPID}
    command: node ./dist/index.js
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "9000"
    depends_on:
      - mongo
    restart: always
    networks:
      - laf_shared_network

  system-client:
    image: lafyun/system-client:0.8.0
    networks:
      - laf_shared_network

  app-console:
    image: lafyun/app-console:0.8.0
    networks:
      - laf_shared_network

networks:
  laf_shared_network:
    external: true

volumes:
  db-data:
  oss-data:
  etcd-data:
